
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-6pm-4
owner: ucsb-cs156-f23
repo_name: team02-f23-6pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjkwNjczMzc2","is_bot":false,"login":"dayvidwang","name":""},"headRefName":"dayvidwang-Articles-delete","number":79,"title":"DELETE endpoint for a specific record in Articles.","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-4/pull/79"},{"author":{"id":"MDQ6VXNlcjkwNjczMzc2","is_bot":false,"login":"dayvidwang","name":""},"headRefName":"dayvidwang-Articles-put","number":78,"title":"PUT endpoint for single record in Articles","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-4/pull/78"},{"author":{"id":"MDQ6VXNlcjkwNjczMzc2","is_bot":false,"login":"dayvidwang","name":""},"headRefName":"dayvidwang-Articles-get","number":77,"title":"GET endpoint to fetch a single article from Articles","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-4/pull/77"},{"author":{"id":"MDQ6VXNlcjkwNjczMzc2","is_bot":false,"login":"dayvidwang","name":""},"headRefName":"dayvidwang-Articles-controller","number":76,"title":"Articles Controller and Tests","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-4/pull/76"},{"author":{"id":"U_kgDOBclckQ","is_bot":false,"login":"allychu","name":""},"headRefName":"allychu-UCSBOrganization-delete","number":75,"title":"Added UCSB Organization Delete Endpoint ","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-4/pull/75"}]
