
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-6pm-4
owner: ucsb-cs156-f23
repo_name: team02-f23-6pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjU0OTAxOTc3","is_bot":false,"login":"chelseastoner","name":"Chelsea Stoner"},"headRefName":"Chelsea-DiningCommons-DELETE-endpoint","number":70,"title":"Add Dining Commons Menu Items DELETE endpoint","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-4/pull/70"},{"author":{"id":"MDQ6VXNlcjU0OTAxOTc3","is_bot":false,"login":"chelseastoner","name":"Chelsea Stoner"},"headRefName":"Chelsea-DiningCommons-GET-endpoint","number":68,"title":"Add Dining Commons Menu Items GET endpoint","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-4/pull/68"},{"author":{"id":"U_kgDOBclckQ","is_bot":false,"login":"allychu","name":""},"headRefName":"allychu-UCSBOrganization-controller-get-post","number":67,"title":"Create UCSB Organization Item Controller and Controller Tests","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-4/pull/67"},{"author":{"id":"MDQ6VXNlcjU0OTAxOTc3","is_bot":false,"login":"chelseastoner","name":"Chelsea Stoner"},"headRefName":"Chelsea-DiningCommons-create-controller","number":65,"title":"Create Dining Commons Menu Item Controller and Tests","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-4/pull/65"},{"author":{"id":"MDQ6VXNlcjkwNjczMzc2","is_bot":false,"login":"dayvidwang","name":""},"headRefName":"dayvidwang-Articles-create-db","number":44,"title":"adding database table for Articles","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-4/pull/44"}]
