
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-6pm-4
owner: ucsb-cs156-f23
repo_name: team02-f23-6pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjgwMDY1NjAx","is_bot":false,"login":"sumitgupta314","name":"Sumit Gupta"},"headRefName":"sg-RecommendationRequest-add_get_post_api_calls","number":66,"title":"Sg recommendation request add get post api calls","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-4/pull/66"},{"author":{"id":"MDQ6VXNlcjU0OTAxOTc3","is_bot":false,"login":"chelseastoner","name":"Chelsea Stoner"},"headRefName":"Chelsea-DiningCommons-create-controller","number":65,"title":"Create Dining Commons Menu Item Controller and Tests","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-4/pull/65"},{"author":{"id":"U_kgDOBclckQ","is_bot":false,"login":"allychu","name":""},"headRefName":"allychu-UCSBOrganization-create-db","number":59,"title":"Create Database Table for UCSBOrganization","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-4/pull/59"},{"author":{"id":"MDQ6VXNlcjgwMDY1NjAx","is_bot":false,"login":"sumitgupta314","name":"Sumit Gupta"},"headRefName":"sg-RecommendationRequest-put_endpoint","number":58,"title":"Added PUT endpoint and tests for Recommendation Request","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-4/pull/58"},{"author":{"id":"U_kgDOBXmMcA","is_bot":false,"login":"darylou","name":"Daryl Ou"},"headRefName":"darylou-MenuItemReview-add-put","number":56,"title":"do - added put functionality to MenuItemReview","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-4/pull/56"},{"author":{"id":"U_kgDOBXmMcA","is_bot":false,"login":"darylou","name":"Daryl Ou"},"headRefName":"darylou-MenuItemReview-add-get-single","number":49,"title":"do - add get for a single review for MenuItemReviews","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-4/pull/49"},{"author":{"id":"U_kgDOBXmMcA","is_bot":false,"login":"darylou","name":"Daryl Ou"},"headRefName":"darylou-MenuItemReview-add-delete","number":48,"title":"do - added MenuItemReview delete route","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-4/pull/48"},{"author":{"id":"MDQ6VXNlcjkwNjczMzc2","is_bot":false,"login":"dayvidwang","name":""},"headRefName":"dayvidwang-Articles-create-db","number":44,"title":"adding database table for Articles","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-4/pull/44"}]
