
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-6pm-4
owner: ucsb-cs156-f23
repo_name: team02-f23-6pm-4
pull_requests: [{"author":{"id":"U_kgDOBXmMcA","is_bot":false,"login":"darylou","name":"Daryl Ou"},"headRefName":"darylou-MenuItemReview-create-db","number":45,"title":"Create Database Table for MenuItemReview","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-4/pull/45"},{"author":{"id":"MDQ6VXNlcjkwNjczMzc2","is_bot":false,"login":"dayvidwang","name":""},"headRefName":"dayvidwang-Articles-create-db","number":44,"title":"adding database table for Articles","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-4/pull/44"}]
